apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: argent
  namespace: argent-prd
spec:
  image: ghcr.io/neverdecel/argent
  interval: 5m
  secretRef:
    name: ghcr-creds-prd
