apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argent
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - argent.neverdecel.com
      secretName: argent-prd-tls
  rules:
    - host: argent.neverdecel.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argent
                port:
                  number: 80
