apiVersion: v1
kind: Service
metadata:
  name: argent
  labels:
    app: argent
spec:
  type: ClusterIP
  selector:
    app: argent
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
